name: hello-world
on:
  push:
    branches:
    - 'main'
jobs:
  my-job:
    runs-on: windows
    container:
      image: ghcr.io/anu1101/hello-world:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    steps:
      - run: echo "hello world"
