name: hello-world
on:
  push:
    branches:
    - 'main'
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anu1101/hello-world:latest
    steps:
      - run: echo "hello world"
